spring:
  application:
    name: SERVICE-REGISTRY

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    eviction-interval-timer-in-ms: 1000