server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:8082
  cloud:
    gateway:
      routes:
        - id: dma-service
          uri: lb://DMA-SERVICE
          predicates:
            - Path=/api/dma/**
