server:
  port: ${gateway-server-port}

spring:
  application:
    name: API-GATEWAY
  profiles:
    active:
      - dev
  config:
    import: configserver:http://localhost:8082
  cloud:
    gateway:
      routes:
        - id: dma-service
          uri: lb://DMA-SERVICE
          predicates:
            - Path=/api/dma/**

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/product/**

management:
  endpoints:
    web:
      exposure:
        include: "*"