server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: dma-service
          uri: lb://DMA-SERVICE
          predicates:
            - Path=/dma/**

eureka:
  client:
    serviceUrl:
      defaultZone : http://localhost:8761/eureka/