server:
  port: ${product-server-port}
  servlet:
    context-path: /api/product

spring:
  application:
    name: PRODUCT-SERVICE
  profiles:
    active:
      - dev
  config:
    import: configserver:http://localhost:8082
  datasource:
    url: jdbc:mysql://localhost:3306/${product-database}?createDatabaseIfNotExist=true
    username: ${mysql-username}
    password: ${mysql-password}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      customerService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      customerService:
        maxRetryAttempts: 5
        waitDuration: 10s