server:
  port: 8082

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/NiteenRC/product-induct-app/tree/master/configuration
          default-label: master

management:
  endpoints:
    web:
      exposure:
        include: "*"